### ISSUE TITLE
ACME Mode is unable to issue Certificates

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#86]
```sh

$ kubectl describe challenges.acme.cert-manager.io -n kube-dashboard
...
Error accepting challenge: Head https://acme-v02.api.letsencrypt.org/acme/new-nonce: x509: certificate is valid for ingress.local, not acme-v02.api.letsencrypt.org

$ kubectl describe orders.acme.cert-manager.io -n kube-dashboard

Status:
  Authorizations:
    Challenges:
      Token:     8YEOCFNdLSxsF5LX68qQ1eotYT93pKlxChryPWmQC2w
      Type:      http-01
      URL:       https://acme-v02.api.letsencrypt.org/acme/chall-v3/1650596565/sVDeBQ


```

**Comment by gprossliner** [comment]
It seems like Lets Encrypt uses https: instead of http: to send the ACME Challenge. This can't work, because to use https: we need a Certificate:

for(;;) { 
certificate is issued by ACME; 
ACME need to send the Challange with https:;
which needs a Certificate,;
}

certmanager don't specify anything special: [HTTP01](https://cert-manager.io/docs/configuration/acme/http01/)

[ChallengeTypes](https://letsencrypt.org/docs/challenge-types/#http-01-challenge)
> When redirected to an HTTPS URL, it does not validate certificates 
> (since this challenge is intended to bootstrap valid certificates, it may encounter 
> self-signed or expired certificates along the way).

So we need to investigate further
